### ISSUE TITLE
Starting gear, in combination with a class system (just std class with std gear for now)

### ISSUE THREAD

**Issue by TheRoot89** [TheRoot89/DungeonGen#15]

**Comment by TheRoot89** [comment]
I opt for: stone sword, bow, 1 arrow :shipit:

**Comment by Lionbug** [comment]
maybe health potions and stuff

**Comment by TheRoot89** [comment]
Found the following:
`player.getInventory().clear();`
und zum setzen:
`p.getInventory.add(new ItemStack(Material.MUSHROOM_SOUP, 1));`
oder
`ItemStack[] items = {new ItemStack(Material.BREAD), new ItemStack(Material.MUSHROOM_SOUP)};
player.getInventory().addItem(items);`

**Comment by Lionbug** [comment]
We'll do a class system later... ... ...
