### ISSUE TITLE
Maze generator

### ISSUE THREAD

**Issue by TheRoot89** [TheRoot89/DungeonGen#33]
We cannot build mazes for ourselves - we would know the solution 😞 
* Solution: There are many Maze generation algorithms out there. We will need give the target "to-be-mazed" area to the algo in the form of a grid and have it generate one. Then this grid needs to be set in blocks into the generated room and entrance + exit need to be carved. Thus, the maze will have to be fully connected, i.e. each point in the maze has to be reachable in principle from each other.
Here is a link: [Maze algos](http://weblog.jamisbuck.org/2010/12/27/maze-generation-recursive-backtracking)  
I favor "recursive backtracking" if it is not too hardware hungry, as it generates very nice mazes with lots of long dead ends 😈

**Comment by TheRoot89** [comment]
Steps are:
* new sub-package "utils" where such helping algorithms shall go
* First implementation of that algo as "RecursiveBacktracking":
    * Inputs:
        * Width and height of the wanted maze grid.
        * The random number generator or seed of the plugin, so the maze will look the same if the same seed is used (?). Do we want this, @Lionbug ?
    * Outputs: 
        * Some data format to know where in between the grid cells are walls an where not. For an example, see the link above. One possibility is to save whether there is a northern wall and whether there is an eastern wall for each cell (binary grids). The northern wall of one cell at the same time then is the southern wall of the one on top. (Same is valid for east and west)
    * We then have to decide how big the walls and passageways are and then have to generate these  in the designated area according to the blueprint we got. Example: passagewaysWidth=2

**Comment by Lionbug** [comment]
I´d say the point of a maze is to be random, so we do not, in fact, want it to look the same ¯\_(ツ)_/¯
Converting the code will probably be beyond me but i shall think on the proportions of the walls and passages i guess, neuf-neuf

**Comment by TheRoot89** [comment]
Nice, let's say the width of ways and walls can be set by the room that needs a maze. Example: way = 2 blocks wide, wall = 1 block wide. Creators could then have rather claustrophobic, small mazes, or giant, impressing ones =)  

The entry and exit could be anywhere at the boundaries of that maze (rectangular) region. However, both should 'hit' a way correctly in between walls. I think it would then be easiest, if not the maze generator cared for the outer walls, but the room does. Then entry and exit are fixed by the gaps the creator leaves open in these confines. He is then responsible himself the positions of ways and walls fit correctly to that. In the above example that would be: blocks 1+2 correspond to a way, then 3 is a wall, 4 +5 are a way, etc.  

Also the region a room wants to be mazed has to have a total block width and height that is an integer multiple of way-width + wall-width, e.g. 3 blocks. This has to be ensured as well, for example in the initial yml 'sanity' check.  

I suggest requesting a maze for a given region is another type of 'task' for room. The region and way/wall widths may then be given in the yml as well. The room will take care of the generation then when loading all the tasks. Periodic execution of that task will probably not make sense though.

No worries, we can go through the code together once it works ;)

**Comment by TheRoot89** [comment]
So it works, but some ToDos are left.

For example, the maze should be "nice", so the exit has to be positioned where the path is longest OR the maze is recalculated. (prefering first option)
* count steps for each cell beginning from entry: done
* give maze the ability to carve an exit at the best position: done
  It does so by replacing outer walls with air up to the thickness of the defined wallWidth parameter. It is possible to select the four walls of the rectangle individually to allow for the exit to spawn there, as well as have a hole in the floor carved (1 block deep) as exit.

**Comment by TheRoot89** [comment]
Also add the option to have a floor hole instead of a wall exit - also at the longest dist from the entry!
Edit:
Added but there are still some bugs to be fixed. Also the lighting problem is apparent.

**Comment by TheRoot89** [comment]
Done and merged :)
